[functions]
  included_files = ["views/**", "dist/**"]

[build]
  command = "npm run build"
  functions = "functions"


[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200

# [[redirects]]
#   from = "/static/*"
#   to = "/.netlify/functions/server/static/*"
#   status = 200
